2013-08-08 09:37:36-0400 [-] Log opened.
2013-08-08 09:37:36-0400 [-] twistd 13.1.0 (/usr/bin/python 2.7.3) starting up.
2013-08-08 09:37:36-0400 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2013-08-08 09:37:36-0400 [-] [32276] Upon execvpe 32276 ['32276'] in environment id 49821072
2013-08-08 09:37:36-0400 [-] [32276] :Traceback (most recent call last):
2013-08-08 09:37:36-0400 [-] [32276]   File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 403, in _fork
2013-08-08 09:37:36-0400 [-] [32276]     path, uid, gid, executable, args, environment)
2013-08-08 09:37:36-0400 [-] [32276]   File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 453, in _execChild
2013-08-08 09:37:36-0400 [-] [32276]     os.execvpe(executable, args, environment)
2013-08-08 09:37:36-0400 [-] [32276]   File "/usr/lib/python2.7/os.py", line 353, in execvpe
2013-08-08 09:37:36-0400 [-] [32276]     _execvpe(file, args, env)
2013-08-08 09:37:36-0400 [-] [32276]   File "/usr/lib/python2.7/os.py", line 380, in _execvpe
2013-08-08 09:37:36-0400 [-] [32276]     func(fullname, *argrest)
2013-08-08 09:37:36-0400 [-] [32276] OSError: [Errno 2] No such file or directory
2013-08-08 09:37:37-0400 [-] [32276] Upon execvpe 32276 ['32276'] in environment id 49815264
2013-08-08 09:37:37-0400 [-] [32276] :Traceback (most recent call last):
2013-08-08 09:37:37-0400 [-] [32276]   File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 403, in _fork
2013-08-08 09:37:37-0400 [-] [32276]     path, uid, gid, executable, args, environment)
2013-08-08 09:37:37-0400 [-] [32276]   File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 453, in _execChild
2013-08-08 09:37:37-0400 [-] [32276]     os.execvpe(executable, args, environment)
2013-08-08 09:37:37-0400 [-] [32276]   File "/usr/lib/python2.7/os.py", line 353, in execvpe
2013-08-08 09:37:37-0400 [-] [32276]     _execvpe(file, args, env)
2013-08-08 09:37:37-0400 [-] [32276]   File "/usr/lib/python2.7/os.py", line 380, in _execvpe
2013-08-08 09:37:37-0400 [-] [32276]     func(fullname, *argrest)
2013-08-08 09:37:37-0400 [-] [32276] OSError: [Errno 2] No such file or directory
2013-08-08 09:37:40-0400 [-] [32276] Upon execvpe 32276 ['32276'] in environment id 49841536
2013-08-08 09:37:40-0400 [-] [32276] :Traceback (most recent call last):
2013-08-08 09:37:40-0400 [-] [32276]   File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 403, in _fork
2013-08-08 09:37:40-0400 [-] [32276]     path, uid, gid, executable, args, environment)
2013-08-08 09:37:40-0400 [-] [32276]   File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 453, in _execChild
2013-08-08 09:37:40-0400 [-] [32276]     os.execvpe(executable, args, environment)
2013-08-08 09:37:40-0400 [-] [32276]   File "/usr/lib/python2.7/os.py", line 353, in execvpe
2013-08-08 09:37:40-0400 [-] [32276]     _execvpe(file, args, env)
2013-08-08 09:37:40-0400 [-] [32276]   File "/usr/lib/python2.7/os.py", line 380, in _execvpe
2013-08-08 09:37:40-0400 [-] [32276]     func(fullname, *argrest)
2013-08-08 09:37:40-0400 [-] [32276] OSError: [Errno 2] No such file or directory
2013-08-08 09:37:44-0400 [-] [32276] Upon execvpe 32276 ['32276'] in environment id 49839616
2013-08-08 09:37:44-0400 [-] [32276] :Traceback (most recent call last):
2013-08-08 09:37:44-0400 [-] [32276]   File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 403, in _fork
2013-08-08 09:37:44-0400 [-] [32276]     path, uid, gid, executable, args, environment)
2013-08-08 09:37:44-0400 [-] [32276]   File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 453, in _execChild
2013-08-08 09:37:44-0400 [-] [32276]     os.execvpe(executable, args, environment)
2013-08-08 09:37:44-0400 [-] [32276]   File "/usr/lib/python2.7/os.py", line 353, in execvpe
2013-08-08 09:37:44-0400 [-] [32276]     _execvpe(file, args, env)
2013-08-08 09:37:44-0400 [-] [32276]   File "/usr/lib/python2.7/os.py", line 380, in _execvpe
2013-08-08 09:37:44-0400 [-] [32276]     func(fullname, *argrest)
2013-08-08 09:37:44-0400 [-] [32276] OSError: [Errno 2] No such file or directory
2013-08-08 09:37:52-0400 [-] [32276] Upon execvpe 32276 ['32276'] in environment id 49821072
2013-08-08 09:37:52-0400 [-] [32276] :Traceback (most recent call last):
2013-08-08 09:37:52-0400 [-] [32276]   File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 403, in _fork
2013-08-08 09:37:52-0400 [-] [32276]     path, uid, gid, executable, args, environment)
2013-08-08 09:37:52-0400 [-] [32276]   File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 453, in _execChild
2013-08-08 09:37:52-0400 [-] [32276]     os.execvpe(executable, args, environment)
2013-08-08 09:37:52-0400 [-] [32276]   File "/usr/lib/python2.7/os.py", line 353, in execvpe
2013-08-08 09:37:52-0400 [-] [32276]     _execvpe(file, args, env)
2013-08-08 09:37:52-0400 [-] [32276]   File "/usr/lib/python2.7/os.py", line 380, in _execvpe
2013-08-08 09:37:52-0400 [-] [32276]     func(fullname, *argrest)
2013-08-08 09:37:52-0400 [-] [32276] OSError: [Errno 2] No such file or directory
2013-08-08 09:38:08-0400 [-] [32276] Upon execvpe 32276 ['32276'] in environment id 49815264
2013-08-08 09:38:08-0400 [-] [32276] :Traceback (most recent call last):
2013-08-08 09:38:08-0400 [-] [32276]   File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 403, in _fork
2013-08-08 09:38:08-0400 [-] [32276]     path, uid, gid, executable, args, environment)
2013-08-08 09:38:08-0400 [-] [32276]   File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 453, in _execChild
2013-08-08 09:38:08-0400 [-] [32276]     os.execvpe(executable, args, environment)
2013-08-08 09:38:08-0400 [-] [32276]   File "/usr/lib/python2.7/os.py", line 353, in execvpe
2013-08-08 09:38:08-0400 [-] [32276]     _execvpe(file, args, env)
2013-08-08 09:38:08-0400 [-] [32276]   File "/usr/lib/python2.7/os.py", line 380, in _execvpe
2013-08-08 09:38:08-0400 [-] [32276]     func(fullname, *argrest)
2013-08-08 09:38:08-0400 [-] [32276] OSError: [Errno 2] No such file or directory
2013-08-08 09:38:28-0400 [-] Received SIGTERM, shutting down.
2013-08-08 09:38:28-0400 [-] Main loop terminated.
2013-08-08 09:38:28-0400 [-] Server Shut Down.
